version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass123

  backend:
    build: ./backend
    container_name: backend-app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:pass123@mongodb-container:27017/vma_db

  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
